#!/bin/sh /etc/rc.common

#Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#SPDX-License-Identifier: BSD-3-Clause-Clear

START=99
USE_PROCD=1

start_service() {

# Sleep for 20 seconds before starting
    sleep 20
  
      # Bring up the interface
    ifconfig mhi_swip0 10.10.10.3 up
    ifconfig mhi_swip0

    # Add neighbor if not already present
    ip neighbor show dev mhi_swip0 | grep -q 10.10.10.7 || \
        ip neigh add 10.10.10.7 lladdr 70:71:aa:4b:29:77 nud permanent dev mhi_swip0

    # Start the crashcollect binary using procd
    procd_open_instance
    procd_set_param command /usr/sbin/crashcollect
    procd_set_param respawn
    procd_close_instance
}

