#! /bin/sh /etc/rc.common

# Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear


START=97
STOP=02

USE_PROCD=1

start_service() {
    if [ "$(/sbin/abctl --boot_slot)" = "_a" ] || [ "$(/sbin/abctl --boot_slot)" = "_b" ]; then
        /sbin/abctl --set_success
    else
        echo "invalid boot slot" > /dev/kmsg
        exit 1
    fi
}

stop_service() {
    echo "stoping the service"
}
