#!/bin/sh /etc/rc.common

#Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#SPDX-License-Identifier: BSD-3-Clause-Clear

START=15
STOP=99

USE_PROCD=1
CONFIG_FILE="/etc/log-conf.json"

start_service() {
        local interval_min

        if [ -f "$CONFIG_FILE" ]; then
                interval_min=$(grep -o '"interval_min":[[:space:]]*[0-9]*' $CONFIG_FILE | grep -o '[0-9]*')
        fi

        procd_open_instance
        procd_set_param command /usr/sbin/log-collector

        if [ -n "$interval_min" ]; then
		local respawn_delay
                respawn_delay=$((interval_min * 60))
                procd_set_param respawn 0 "$respawn_delay" 0
        fi

	procd_close_instance
}

stop_service() {
         echo "Stopping the service"
}

