#!/bin/sh
#Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#SPDX-License-Identifier: BSD-3-Clause-Clear

check_if_boot_dev()
{
	ret_val=`cat /proc/cmdline | grep "androidboot.bootdevice" |wc -l`
	if  [ $ret_val -ne 0 ]; then
		boot_dev_list=`cat /proc/cmdline | awk '{ for ( n=1; n<=NF; n++ ) if($n ~ "androidboot.bootdevice") print $n }' | awk '{split($0,a, "=");print a[2]}'`
		boot_dev=`echo $boot_dev_list | awk '{print $NF}'`
		real_sysfs_path=`realpath /sys/class/block/$DEVICENAME`
		ret_val=`echo $real_sysfs_path | grep /sys/devices/ | grep $boot_dev | wc -l`
	fi
	echo $ret_val
}

if [ "$ACTION" = add -o "$ACTION" = remove ]; then
	result=`check_if_boot_dev $DEVICENAME`
	if [ $result -ne 1 ]; then
		case "$DEVICENAME" in
			mmcblk[0-9]*p[0-9]* | [hs]d[a-z][0-9]*)
		. /etc/scripts/automountsdcard.sh "$DEVICENAME" "$ACTION"
		esac
	fi
fi
