#!/bin/sh /etc/rc.common

#Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

START=14
STOP=85

USE_PROCD=1
PROCD_DEBUG=1

start_service() {
        if [ -x "/usr/bin/servicemanager" ]; then
                procd_open_instance
                procd_set_param command /usr/bin/servicemanager
                procd_set_param respawn 3600 1 0
                procd_set_param user system
                procd_set_param group system
                procd_close_instance
        fi
}

stop_service() {
        echo "Stopping servicemanager service"
}
